### ISSUE TITLE
chore: 여러가지 디자인, 경로 수정

### ISSUE THREAD

**Issue by cogns** [samtuap/dongsanginong-client#115]
## 이슈 설명

공지생성 등록 닫기 시 null처리
등록 성공 시 새로고침
구매자 상품리뷰 페이지 타이틀 h4 수정
공지 디테일 farmId 입력 안되는 오류 수정

## ✅ Todo 

- [ ] 공지생성 등록 닫기 시 null처리
- [ ] 등록 성공 시 새로고침
- [ ] 구매자 상품리뷰 페이지 타이틀 h4 수정
- [ ] 공지 디테일 farmId 입력 안되는 오류 수정
