### ISSUE TITLE
fix: farm 목록 화면 수정, fcm token 에러 수정

### ISSUE THREAD

**Issue by clean2001** [samtuap/dongsanginong-client#120]
## 이슈 설명

자잘한 것들 수정

## ✅ Todo 

- [x] fcm token 저장 에러 수정
- [ ] farm 목록 화면 디벨롭하기
- [ ] 메인 페이지에 링크 연결
- [ ] 메인 페이지, farm list 즐겨찾기 누르기 API 연동
- [ ] 로그아웃시 indexed DB 처리하기
