### ISSUE TITLE
chore&feat: 라이브 관련 추가 및 수정 요청사항 적용 

### ISSUE THREAD

**Issue by H-Yeji** [samtuap/dongsanginong-client#138]
## 이슈 설명

- 라이브 관련 추가 및 수정 요청사항 적용 

## ✅ Todo 

- [x] 라이브 목록 디자인 디벨롭 - 라이브 생성시 카테고리 항목 추가 
- [x] myfarm 없으면 live 시작할 때 모달창 띄워 myfarm 생성 페이지로 라우팅 
- [x] 방송자가 먼저 라이브를 종료했을 때 > 시청자 쪽에 종료 안내 출력
- [x] 시청자가 나가기 버튼 눌렀을 때 모달 멘트 변경
