### ISSUE TITLE
fix: 담당 파트 디자인 및 디테일 수정

### ISSUE THREAD

**Issue by tteia** [samtuap/dongsanginong-client#139]
## 이슈 설명

담당 파트 디자인 수정

## ✅ Todo 

- [x] 비밀번호 변경 카드 제거
- [x] 처음에는 농장 정보 뜨기 > 수정하기 누르면 수정 형식으로 변경 > 저장하기
- [ ] 패키지 리스트 디자인 수정
- [ ] 우편번호 등록 시 수정할 수 없게 하기
- [ ] 구매자 회원 배송 내역이 연결 되어있지 않음 → 링크 걸기
- [ ] 회원 정보 수정 > 위 아래로 구분
- [ ] 마이 페이지 > 내 정보 보기 메뉴 추가
- [ ] 즐겨찾기 및 정기 구독 으로 메뉴 이름 변경
