### ISSUE TITLE
fix: 노션 중간점검 후 수정사항 처리

### ISSUE THREAD

**Issue by cogns** [samtuap/dongsanginong-client#165]
## 이슈 설명

노션 중간점검 후 수정사항 처리

## ✅ Todo 

- [ ] 리뷰 작성 페이지 수정
- [ ] 쿠폰 생성시 날짜를 선택하지 않아도 달력 모달 꺼지도록 수정
- [ ] 공지 작성중에 “닫기”버튼 클릭 시 모달 창 한번 더 추가
- [ ] 좋아요 색깔 바꾸기
