### ISSUE TITLE
fix: 농장 생성 화면 수정

### ISSUE THREAD

**Issue by vydndrl** [samtuap/dongsanginong-client#175]
## 이슈 설명
- 배너 이미지 등록 시 버튼 수정
- 농장 처음 생성 시 모달 수정
- 이미지 해상도 수정

## ✅ Todo 

- [ ] 배너 이미지 등록 시 버튼 수정
- [ ] 농장 처음 생성 시 모달 수정
- [ ] 이미지 해상도 수정
