### ISSUE TITLE
fix: 결제 화면 관련 수정

### ISSUE THREAD

**Issue by clean2001** [samtuap/dongsanginong-client#245]
## 이슈 설명

결제 화면 관련 수정 사항입니다.

+ 판매자 대시보드 매출 부분

## ✅ Todo 

- [x] 결제 페이지 > 세일 가격 표시
- [x] 결제 페이지 > 배송지 변경 버튼 누르면 변경 모달 표시
- [x] 결제 완료 페이지 > 주문 번호 수정
- [x] 판매자 페이지 > 주문 번호 수정
- [x] 판매자 페이지 > 매출 내역  페이지네이션 수정
- [x] 판매자 페이지 > 하단에 10page 없애기
