### ISSUE TITLE
feat: 일반 회원 마이 페이지 구현

### ISSUE THREAD

**Issue by tteia** [samtuap/dongsanginong-client#27]
## 이슈 설명

<img width="1048" alt="스크린샷 2024-09-30 오후 5 39 28" src="https://github.com/user-attachments/assets/85606915-3890-4931-8647-d7667e73d9c4">
일반 회원 정보 조회 페이지 구현

## ✅ Todo 

- [x] 사이드 메뉴 구현
- [x] 정보 조회 페이지 구현
- [x] 회원 탈퇴 버튼 클릭 시 회원 탈퇴 구현
