### ISSUE TITLE
chore: 상품 등록 시 에디터 추가 및 농장 생성 후 id 저장

### ISSUE THREAD

**Issue by vydndrl** [samtuap/dongsanginong-client#270]
## 이슈 설명
- 에디터 마크다운 오류
- 새로 가입한 판매자 농장 생성 시 farmId 저장
- 상품 등록 시 에디터로 상세 정보 등록

## ✅ Todo 

- [ ] 에디터 마크다운 버튼 삭제
- [ ] 새로 가입한 판매자 농장 생성 시 farmId 저장
- [ ] 상품 등록 시 에디터로 상세 정보 등록
