### ISSUE TITLE
feat: 공지사항 삭제 및 alert메시지 모달로 수정

### ISSUE THREAD

**Issue by cogns** [samtuap/dongsanginong-client#76]
## 이슈 설명

공지사항 삭제 및 alert메시지 모달로 수정

## ✅ Todo 

- [ ] 공지사항 삭제 기능 구현
- [ ] 공지 생성, 수정 alert메시지 모달로 변경
- [ ] 판매자 사이드바에 경로 추가
