### ISSUE TITLE
style: farm 페이지, 메인페이지 디자인 디테일 수정

### ISSUE THREAD

**Issue by clean2001** [samtuap/dongsanginong-client#97]
## ✅ Todo 

- [x]  메인페이지와 농장 페이지에서 슬라이드의 쩜쩜이 3개로 고정돼있는것 ⇒ 유동적으로 되도록 변경
- [ ]  메인 페이지에서 글자를 순위가 있는 곳과 정렬 맞추기
- [ ]  농장 페이지, 메인페이지에서 너무 글자수 길면 하트가 아래로 내려감 ⇒ height 늘리기
- [ ]  요소가 두개만 있을때는 가까이 되도록 간격 수정
- [ ] footer 추가
